<?php

namespace Database\Seeders;

use App\Models\Prompt;
use Illuminate\Database\Seeder;

class PromptSeeder extends Seeder
{
    public function run(): void
    {
        $prompts = [
            // PORTRAIT (category_id=1)
            ['category_id'=>1,'title'=>'Golden Hour Cinematic Portrait','prompt_text'=>'A stunning cinematic portrait of a young woman with flowing auburn hair, golden hour lighting casting warm orange and amber tones across her face, bokeh background of blurred city lights, shot with 85mm lens, shallow depth of field, photorealistic, 8K resolution, professional photography','description'=>'Foto potret dramatis dengan pencahayaan golden hour yang hangat','ai_tool'=>'Midjourney','style_tags'=>'golden hour, bokeh, cinematic, photorealistic','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_1.png'],
            ['category_id'=>1,'title'=>'Dark Moody Male Portrait','prompt_text'=>'Dark and moody portrait of a mysterious man in his 30s, dramatic side lighting, deep shadows, sharp facial features, slight stubble, wearing a dark leather jacket, black background, high contrast photography, analog film grain, extremely detailed, hyperrealistic','description'=>'Potret pria dengan gaya gelap dan dramatis','ai_tool'=>'Midjourney','style_tags'=>'dark, moody, high contrast, dramatic','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_2.png'],
            ['category_id'=>1,'title'=>'Ethereal Fantasy Portrait','prompt_text'=>'Ethereal portrait of a woman with translucent glowing skin, surrounded by floating cherry blossom petals, soft diffused lighting, pastel pink and lavender color palette, otherworldly beauty, flowing white silk dress, dreamy atmosphere, ultra sharp, 8K','description'=>'Potret wanita dengan nuansa ethereal dan bunga sakura','ai_tool'=>'DALL-E 3','style_tags'=>'ethereal, dreamy, glowing, blossom','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_3.png'],
            ['category_id'=>1,'title'=>'Street Style Urban Portrait','prompt_text'=>'Candid street photography style portrait of a young Asian woman in urban Tokyo, wearing oversized vintage clothing, neon signs reflected in rain puddles behind her, grain film photography aesthetic, Kodak Portra 400 color palette, natural expressions, life on the street','description'=>'Potret street style di jalanan Tokyo yang ramai','ai_tool'=>'Stable Diffusion','style_tags'=>'street, urban, Tokyo, film grain, candid','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_4.png'],
            // LANDSCAPE (category_id=2)
            ['category_id'=>2,'title'=>'Epic Mountain Sunrise','prompt_text'=>'Breathtaking panoramic landscape of majestic snow-capped mountains at sunrise, dramatic orange and pink clouds reflecting on a perfectly still alpine lake in the foreground, misty valleys, god rays breaking through clouds, ultra wide angle shot, hyper detailed, award winning photography, National Geographic style','description'=>'Pemandangan pegunungan epik saat matahari terbit','ai_tool'=>'Midjourney','style_tags'=>'mountain, sunrise, panoramic, epic, lake','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_5.png'],
            ['category_id'=>2,'title'=>'Stormy Ocean Waves','prompt_text'=>'Powerful stormy ocean seascape, massive 30-foot waves crashing against jagged dark rocks, dramatic storm clouds, lightning illuminating the scene, seafoam and mist flying through the air, deep teal and dark grey color palette, raw nature power, long exposure photography effect, cinematic','description'=>'Lautan badai yang dramatis dan powerful','ai_tool'=>'Midjourney','style_tags'=>'ocean, storm, waves, dramatic, nature','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_6.png'],
            ['category_id'=>2,'title'=>'Enchanted Autumn Forest','prompt_text'=>'Magical autumn forest with towering ancient trees, canopy of crimson and gold leaves filtering dappled golden sunlight, misty forest floor covered in orange and red leaves, a winding mossy path disappearing into the depth, fairytale atmosphere, volumetric light rays, hyper realistic, 8K','description'=>'Hutan musim gugur yang magis dan penuh warna','ai_tool'=>'DALL-E 3','style_tags'=>'autumn, forest, golden, misty, enchanted','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_7.png'],
            ['category_id'=>2,'title'=>'Milky Way Desert','prompt_text'=>'Astrophotography masterpiece of the Milky Way galaxy arching across the night sky above a surreal desert landscape with towering red rock formations, star trails, perfect reflection on a small desert lake in foreground, deep blue and purple cosmic tones, ultra high detail, award winning','description'=>'Galaksi Bima Sakti di atas lanskap gurun yang indah','ai_tool'=>'Midjourney','style_tags'=>'milky way, astrophotography, desert, stars, night sky','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_8.png'],
            // FANTASY (category_id=3)
            ['category_id'=>3,'title'=>'Dragon and Ancient Castle','prompt_text'=>'Epic fantasy illustration of an enormous ancient dragon with scales of midnight blue and silver, perched atop a crumbling gothic castle tower, wings spread wide blocking the full moon, glowing amber eyes, storm clouds swirling around, lightning in the background, epic fantasy oil painting style, ultra detailed','description'=>'Naga megah di atas kastil kuno yang dramatis','ai_tool'=>'Midjourney','style_tags'=>'dragon, fantasy, castle, epic, gothic','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_9.png'],
            ['category_id'=>3,'title'=>'Underwater Mermaid Kingdom','prompt_text'=>'Stunning underwater fantasy scene of a mermaid kingdom with towering bioluminescent coral castles, schools of glowing exotic fish, light rays filtering from the surface above, a mermaid with iridescent scales and flowing hair swimming through, deep ocean blue color palette, fantasy digital art, hyper detailed','description'=>'Kerajaan putri duyung bawah laut yang ajaib','ai_tool'=>'DALL-E 3','style_tags'=>'mermaid, underwater, fantasy, bioluminescent, magical','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_10.png'],
            ['category_id'=>3,'title'=>'Ancient Forest Spirit','prompt_text'=>'Mystical ancient forest spirit deity, towering 50 feet tall, made of living wood and moss, with deer antlers made of twisted branches, glowing green eyes, fireflies and magical spores drifting around it, sacred forest at night with moonlight, Studio Ghibli inspired art style, highly detailed','description'=>'Roh hutan kuno yang mistis dan penuh keajaiban','ai_tool'=>'Midjourney','style_tags'=>'forest spirit, mystical, nature deity, Ghibli, magical','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_11.png'],
            ['category_id'=>3,'title'=>'Ice Queen Palace','prompt_text'=>'Majestic Ice Queen in an enormous throne room carved entirely from glacial blue ice, her gown made of crystalline frost and frozen starlight, intricate ice architecture with towering pillars and vaulted ceilings, snowflakes drifting inside, otherworldly cold beauty, high fantasy digital painting, dramatic lighting','description'=>'Ratu Es yang megah di istana kristal biru','ai_tool'=>'Stable Diffusion','style_tags'=>'ice queen, fantasy, crystal, palace, frost','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_12.png'],
            // CINEMATIC (category_id=4)
            ['category_id'=>4,'title'=>'Blade Runner City Alley','prompt_text'=>'Cinematic shot of a rain-soaked futuristic city alley, inspired by Blade Runner 2049, massive holographic advertisements reflecting on wet cobblestone streets, neon lights in reds and blues, steam rising from grates, silhouette of a lone figure with umbrella, ultra cinematic, anamorphic lens, highly detailed','description'=>'Gang kota futuristik ala Blade Runner 2049','ai_tool'=>'Midjourney','style_tags'=>'blade runner, cyberpunk, neon, rain, cinematic','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_13.png'],
            ['category_id'=>4,'title'=>'Post-Apocalyptic Wasteland','prompt_text'=>'Cinematic wide shot of a lone survivor walking through a post-apocalyptic wasteland, ruins of a massive city in background overrun by nature, golden hour light cutting through toxic orange haze, dramatic god rays, detailed destroyed infrastructure, abandoned vehicles, survival gear, epic cinematic composition, photorealistic','description'=>'Dunia pasca apokalips yang dramatis','ai_tool'=>'DALL-E 3','style_tags'=>'post-apocalyptic, survival, wasteland, cinematic, ruins','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_14.png'],
            ['category_id'=>4,'title'=>'Mafia Boss Portrait','prompt_text'=>'Cinematic film noir portrait of a powerful Italian mafia boss in his 60s, sitting at a mahogany desk in dimly lit 1940s office, three-piece suit, cigar smoke curling, harsh venetian blind shadow across his face, expression of quiet menace, noir photography, extreme attention to detail','description'=>'Potret bos mafia bergaya film noir klasik','ai_tool'=>'Midjourney','style_tags'=>'film noir, mafia, cinematic, 1940s, dramatic lighting','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_15.png'],
            // ARCHITECTURE (category_id=5)
            ['category_id'=>5,'title'=>'Glass Skyscraper Utopia','prompt_text'=>'Futuristic ultra-tall glass and steel skyscraper piercing through clouds, parametric architecture with flowing organic curves and integrated sky gardens at every 10th floor, golden sunlight refracting through the glass panels, birds eye aerial view, architectural visualization, photorealistic 8K render','description'=>'Gedung pencakar langit futuristik dengan taman melayang','ai_tool'=>'Stable Diffusion','style_tags'=>'skyscraper, futuristic, glass, architecture, urban','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_16.png'],
            // SCI-FI (category_id=7)
            ['category_id'=>7,'title'=>'Quantum Computer Visualization','prompt_text'=>'Abstract visualization of a quantum computer processor, glowing quantum bits floating in geometric lattice structure, deep blue and cyan energy streams connecting nodes, cryogenic cooling effects with frost and ice crystals, extreme precision and detail, scientific yet artistic, dark background, 8K render','description'=>'Visualisasi artistik komputer kuantum dengan energi biru','ai_tool'=>'Stable Diffusion','style_tags'=>'quantum, abstract, tech visualization, glowing','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>7,'title'=>'Neon Synthwave City','prompt_text'=>'Retrofuturistic synthwave aesthetic aerial view of a glowing grid-lined city at night, massive neon sun setting on the horizon, purple and pink chromatic color palette, flying cars leaving light trails, chrome surfaces and retro-future architecture, 80s nostalgia meets futurism, vaporwave vibes, ultra sharp','description'=>'Kota retrofuturistik dengan estetika synthwave yang ikonik','ai_tool'=>'Midjourney','style_tags'=>'synthwave, vaporwave, neon, retrofuturistic, 80s','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            // NEW PROMPTS (added by user)
            ['category_id'=>4,'title'=>'Post-Apocalyptic Explorer','prompt_text'=>'A cinematic medium shot of a rugged explorer standing on a cliff looking over a ruined, overgrown modern city. Cinematic lighting, golden hour, dust particles in the air, high detail, photorealistic, dramatic sky.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'cinematic,post-apocalyptic,explorer,golden-hour,ruined-city','is_featured'=>1,'copy_count'=>0,'image_path'=>'images/prompts/prompt_27.png'],
            ['category_id'=>4,'title'=>'Vintage 1970s Road Trip','prompt_text'=>'A grainy 1970s film style photo of a classic muscle car parked on the side of Route 66 at sunset. Warm golden tones, light leaks, nostalgic vibe, high realism, shot on Kodachrome.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'vintage,1970s,muscle-car,sunset,retro','is_featured'=>0,'copy_count'=>0,'image_path'=>'images/prompts/prompt_28.png'],
            ['category_id'=>4,'title'=>'The Last Samurai in Snow','prompt_text'=>'A close-up dramatic portrait of a samurai standing in a bamboo forest during a light snowfall. Intense gaze, detailed armor with intricate textures, cinematic side-lighting, shallow depth of field.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'samurai,cinematic,snow,bamboo-forest,portrait','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>4,'title'=>'Neon Cyberpunk Street','prompt_text'=>'A cinematic shot of a futuristic cyberpunk city street at night, glowing neon signs in Japanese Kanji reflecting on wet asphalt, a lone figure in a techwear jacket walking into the distance, misty atmosphere, captured on 35mm film, anamorphic lens flare.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'cyberpunk,neon,night,techwear,wet-street','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>1,'title'=>'Cyber-Enhancement Portrait','prompt_text'=>'Macro shot of a person face showing a subtle, glowing cybernetic blue circuit pattern embedded under the skin near the eye. Hyper-detailed iris, realistic skin pores, soft studio lighting.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'portrait,cybernetic,macro,sci-fi,skin-detail','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>1,'title'=>'Dual Neon Glow Portrait','prompt_text'=>'A close-up portrait of a young man with sharp features, illuminated by split neon lighting (electric blue and hot pink). Detailed skin texture, water droplets on his face, dark background, shot on 85mm lens, f/1.4, hyper-realistic.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'portrait,neon-lighting,synthwave,hyper-realistic,bokeh','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>1,'title'=>'Wise Old Artisan','prompt_text'=>'A candid street portrait of an old wise artisan in a bustling traditional market. Deep wrinkles, expressive eyes, natural overhead sunlight filtering through canvas roofs, dust motes visible, high-end National Geographic photography style.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'portrait,street-photography,candid,culture,realism','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>1,'title'=>'Avant-Garde High Fashion','prompt_text'=>'A high-fashion studio editorial portrait of a model wearing avant-garde metallic clothing. Sharp focus, dramatic shadow play, minimalist background, professional studio lighting, high contrast black and white.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'fashion,studio,portrait,black-and-white,avant-garde','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>3,'title'=>'Cosmic Astronaut','prompt_text'=>'An astronaut sitting on a bench in the middle of a surreal lavender field, looking up at a giant planet and nebula visible in the night sky. Dreamy atmosphere, ethereal lighting, high detail.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'fantasy,surreal,astronaut,cosmic,space','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>3,'title'=>'Floating Castle Waterfalls','prompt_text'=>'A wide-angle shot of a majestic floating island with a medieval castle and a cascading waterfall pouring into the clouds below. Golden sunlight piercing through clouds, epic fantasy art style, highly detailed landscape.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'fantasy,floating-island,castle,landscape,clouds','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>3,'title'=>'Bioluminescent Crystal Fox','prompt_text'=>'A majestic crystal fox glowing with inner light standing in an enchanted bioluminescent forest at night. Glowing mushrooms on the ground, magical particles floating around, ethereal and hyper-realistic.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'fantasy,mythical-creature,bioluminescent,forest,magical','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>3,'title'=>'Endless Ancient Library','prompt_text'=>'An endless, massive ancient library with towering bookshelves reaching into the clouds, shafts of golden sunlight cutting through the dust, floating ancient books, magical realism.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'fantasy,library,surreal,ancient,magic','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>5,'title'=>'Futuristic Solarpunk City','prompt_text'=>'A wide shot of a futuristic solarpunk city where skyscrapers are integrated with massive vertical gardens, flowing waterfalls, and solar panels. Clean white architecture, flying eco-vehicles, bright sunny day, utopian vibe.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'architecture,solarpunk,futurism,green-city,utopia','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>5,'title'=>'Icelandic Black Sand Beach','prompt_text'=>'A moody landscape shot of a black sand beach in Iceland with massive basalt columns, crashing stormy waves with white foam, a dark dramatic cloudy sky, minimalist and powerful composition.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'landscape,nature,iceland,black-sand,moody','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>5,'title'=>'Cyberpunk Cyber Cafe','prompt_text'=>'Interior shot of a cozy but futuristic cyber-cafe in Seoul, filled with retro CRT monitors mixed with holographic displays, warm ambient lighting, rainy night visible through the window.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'interior,cyberpunk,cyber-cafe,hologram,retro-futurism','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>5,'title'=>'Mountain Misty Temple','prompt_text'=>'A serene ancient temple perched dangerously on top of a misty mountain peak during sunrise. Sea of clouds below, traditional architecture, vibrant autumn orange leaves in the foreground.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'landscape,temple,mountain,mist,sunrise','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>6,'title'=>'Tilt-Shift Miniature New York','prompt_text'=>'A tilt-shift miniature photography shot of a bustling New York intersection. Everything looks like tiny, highly detailed toys and miniature cars, vibrant colors, shallow depth of field.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'photography,tilt-shift,miniature,toy-city,new-york','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>6,'title'=>'High-Speed Orange Splash','prompt_text'=>'A high-speed macro photograph of a slice of orange falling into clear water, creating an explosive and artful splash with tiny water droplets frozen in mid-air. Sharp focus, clean studio background.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'photography,macro,high-speed,water-splash,fruit','is_featured'=>0,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>6,'title'=>'Futuristic Sneaker Commercial','prompt_text'=>'A professional commercial product shot of a futuristic sneaker. Placed on a dark reflective surface, neon accents glowing, smoke texture in the background, sharp focus on the fabric textures, advertising style.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'product-shot,sneaker,advertising,commercial,neon','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
            ['category_id'=>6,'title'=>'Underwater Ethereal Floating','prompt_text'=>'An ethereal underwater shot of a person floating gracefully in deep blue water, sun rays piercing through the surface creating beautiful light patterns, dress fabric swirling around softly.','description'=>'','ai_tool'=>'Gemini (Imagen 3)','style_tags'=>'photography,underwater,ethereal,floating,lighting','is_featured'=>1,'copy_count'=>0,'image_path'=>''],
        ];

        foreach ($prompts as $prompt) {
            Prompt::firstOrCreate(['title' => $prompt['title']], $prompt);
        }
    }
}
